"""initial migration

Revision ID: 4688e4c27cd0
Revises: 
Create Date: 2025-10-07 23:20:28.995775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4688e4c27cd0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_type', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', 'FULL_DAY', name='sessiontype'), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('current_participants', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('coach_name', sa.String(length=100), nullable=False),
    sa.Column('age_group', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FULL', 'CANCELLED', 'COMPLETED', name='sessionstatus'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campus_sessions_id'), 'campus_sessions', ['id'], unique=False)
    op.create_table('discount_codes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_order_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_discount_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_customer', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_codes_code'), 'discount_codes', ['code'], unique=True)
    op.create_index(op.f('ix_discount_codes_id'), 'discount_codes', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('discount_price', sa.Float(), nullable=True),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('img', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tag', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_priority'), 'products', ['priority'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('facebook_id', sa.String(length=255), nullable=True),
    sa.Column('github_id', sa.String(length=255), nullable=True),
    sa.Column('social_profiles', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('newsletter_subscription', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_facebook_id'), 'users', ['facebook_id'], unique=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('campus_bookings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('participant_name', sa.String(length=100), nullable=False),
    sa.Column('participant_email', sa.String(length=255), nullable=False),
    sa.Column('participant_phone', sa.String(length=20), nullable=True),
    sa.Column('participant_age', sa.Integer(), nullable=True),
    sa.Column('participant_position', sa.String(length=50), nullable=True),
    sa.Column('guardian_name', sa.String(length=100), nullable=True),
    sa.Column('guardian_email', sa.String(length=255), nullable=True),
    sa.Column('guardian_phone', sa.String(length=20), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('medical_conditions', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['campus_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campus_bookings_booking_reference'), 'campus_bookings', ['booking_reference'], unique=True)
    op.create_index(op.f('ix_campus_bookings_id'), 'campus_bookings', ['id'], unique=False)
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus'), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'CANCELLED', 'REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('shipping_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('shipping_address', sa.String(length=500), nullable=True),
    sa.Column('shipping_city', sa.String(length=100), nullable=True),
    sa.Column('shipping_state', sa.String(length=100), nullable=True),
    sa.Column('shipping_postal_code', sa.String(length=20), nullable=True),
    sa.Column('shipping_country', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('product_sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_sizes_id'), 'product_sizes', ['id'], unique=False)
    op.create_table('product_tags',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'tag_id')
    )
    op.create_table('product_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_translations_id'), 'product_translations', ['id'], unique=False)
    op.create_index(op.f('ix_product_translations_language_code'), 'product_translations', ['language_code'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('REDSYS', 'PAYPAL', 'STRIPE', name='paymentprovider'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'AUTHORIZED', 'CAPTURED', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'EXPIRED', name='redsyspaymentstatus'), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('provider_order_id', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('success_url', sa.String(length=500), nullable=True),
    sa.Column('failure_url', sa.String(length=500), nullable=True),
    sa.Column('cancel_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_order_id'), 'payments', ['provider_order_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_transaction_id'), 'payments', ['provider_transaction_id'], unique=False)
    op.create_table('payment_refunds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'AUTHORIZED', 'CAPTURED', 'COMPLETED', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'EXPIRED', name='paymentstatus'), nullable=False),
    sa.Column('provider_refund_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_refunds_id'), 'payment_refunds', ['id'], unique=False)
    op.create_index(op.f('ix_payment_refunds_provider_refund_id'), 'payment_refunds', ['provider_refund_id'], unique=False)
    op.create_table('redsys_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('merchant_code', sa.String(length=20), nullable=False),
    sa.Column('terminal', sa.String(length=10), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('ds_order', sa.String(length=255), nullable=False),
    sa.Column('ds_merchant_parameters', sa.Text(), nullable=True),
    sa.Column('ds_signature', sa.String(length=255), nullable=True),
    sa.Column('ds_signature_version', sa.String(length=20), nullable=True),
    sa.Column('response_ds_date', sa.String(length=20), nullable=True),
    sa.Column('response_ds_hour', sa.String(length=10), nullable=True),
    sa.Column('response_ds_amount', sa.String(length=20), nullable=True),
    sa.Column('response_ds_currency', sa.String(length=10), nullable=True),
    sa.Column('response_ds_order', sa.String(length=255), nullable=True),
    sa.Column('response_ds_merchant_code', sa.String(length=20), nullable=True),
    sa.Column('response_ds_terminal', sa.String(length=10), nullable=True),
    sa.Column('response_ds_response', sa.String(length=10), nullable=True),
    sa.Column('response_ds_merchant_data', sa.Text(), nullable=True),
    sa.Column('response_ds_secure_payment', sa.String(length=10), nullable=True),
    sa.Column('response_ds_card_number', sa.String(length=50), nullable=True),
    sa.Column('response_ds_card_brand', sa.String(length=20), nullable=True),
    sa.Column('response_ds_card_type', sa.String(length=20), nullable=True),
    sa.Column('response_ds_card_country', sa.String(length=10), nullable=True),
    sa.Column('response_ds_authorisation_code', sa.String(length=20), nullable=True),
    sa.Column('response_ds_consumer_language', sa.String(length=10), nullable=True),
    sa.Column('response_ds_merchant_parameters', sa.Text(), nullable=True),
    sa.Column('response_ds_signature', sa.String(length=255), nullable=True),
    sa.Column('response_ds_signature_version', sa.String(length=20), nullable=True),
    sa.Column('response_ds_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('response_ds_merchant_identifier', sa.String(length=255), nullable=True),
    sa.Column('response_ds_emv3ds', sa.Text(), nullable=True),
    sa.Column('is_sandbox', sa.Boolean(), nullable=True),
    sa.Column('signature_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('request_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index(op.f('ix_redsys_transactions_ds_order'), 'redsys_transactions', ['ds_order'], unique=False)
    op.create_index(op.f('ix_redsys_transactions_id'), 'redsys_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redsys_transactions_id'), table_name='redsys_transactions')
    op.drop_index(op.f('ix_redsys_transactions_ds_order'), table_name='redsys_transactions')
    op.drop_table('redsys_transactions')
    op.drop_index(op.f('ix_payment_refunds_provider_refund_id'), table_name='payment_refunds')
    op.drop_index(op.f('ix_payment_refunds_id'), table_name='payment_refunds')
    op.drop_table('payment_refunds')
    op.drop_index(op.f('ix_payments_provider_transaction_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_product_translations_language_code'), table_name='product_translations')
    op.drop_index(op.f('ix_product_translations_id'), table_name='product_translations')
    op.drop_table('product_translations')
    op.drop_table('product_tags')
    op.drop_index(op.f('ix_product_sizes_id'), table_name='product_sizes')
    op.drop_table('product_sizes')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_campus_bookings_id'), table_name='campus_bookings')
    op.drop_index(op.f('ix_campus_bookings_booking_reference'), table_name='campus_bookings')
    op.drop_table('campus_bookings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_index(op.f('ix_users_facebook_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_products_priority'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_discount_codes_id'), table_name='discount_codes')
    op.drop_index(op.f('ix_discount_codes_code'), table_name='discount_codes')
    op.drop_table('discount_codes')
    op.drop_index(op.f('ix_campus_sessions_id'), table_name='campus_sessions')
    op.drop_table('campus_sessions')
    # ### end Alembic commands ###
