"""add_customer_contact_fields_to_orders

Revision ID: 6a3269ced195
Revises: 4688e4c27cd0
Create Date: 2025-10-08 11:42:59.209148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3269ced195'
down_revision: Union[str, None] = '4688e4c27cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('customer_first_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('customer_last_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('customer_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customer_phone')
    op.drop_column('orders', 'customer_last_name')
    op.drop_column('orders', 'customer_first_name')
    op.drop_column('orders', 'customer_email')
    # ### end Alembic commands ###
