"""Add campus booking models

Revision ID: 7fa588579ec7
Revises: ab53e1162c9d
Create Date: 2025-08-08 23:18:05.104866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7fa588579ec7"
down_revision: Union[str, None] = "ab53e1162c9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campus_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "session_type",
            sa.Enum("MORNING", "AFTERNOON", "EVENING", "FULL_DAY", name="sessiontype"),
            nullable=False,
        ),
        sa.Column("max_participants", sa.Integer(), nullable=False),
        sa.Column("current_participants", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=False),
        sa.Column("coach_name", sa.String(length=100), nullable=False),
        sa.Column("age_group", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum("OPEN", "FULL", "CANCELLED", "COMPLETED", name="sessionstatus"),
            nullable=False,
        ),
        sa.Column("is_featured", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campus_sessions_id"), "campus_sessions", ["id"], unique=False
    )
    op.create_table(
        "campus_bookings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("participant_name", sa.String(length=100), nullable=False),
        sa.Column("participant_email", sa.String(length=255), nullable=False),
        sa.Column("participant_phone", sa.String(length=20), nullable=True),
        sa.Column("participant_age", sa.Integer(), nullable=True),
        sa.Column("participant_position", sa.String(length=50), nullable=True),
        sa.Column("guardian_name", sa.String(length=100), nullable=True),
        sa.Column("guardian_email", sa.String(length=255), nullable=True),
        sa.Column("guardian_phone", sa.String(length=20), nullable=True),
        sa.Column("experience_level", sa.String(length=50), nullable=True),
        sa.Column("medical_conditions", sa.Text(), nullable=True),
        sa.Column("emergency_contact_name", sa.String(length=100), nullable=True),
        sa.Column("emergency_contact_phone", sa.String(length=20), nullable=True),
        sa.Column("special_requests", sa.Text(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "CONFIRMED", "CANCELLED", "COMPLETED", name="bookingstatus"
            ),
            nullable=False,
        ),
        sa.Column("booking_reference", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["campus_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campus_bookings_booking_reference"),
        "campus_bookings",
        ["booking_reference"],
        unique=True,
    )
    op.create_index(
        op.f("ix_campus_bookings_id"), "campus_bookings", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_campus_bookings_id"), table_name="campus_bookings")
    op.drop_index(
        op.f("ix_campus_bookings_booking_reference"), table_name="campus_bookings"
    )
    op.drop_table("campus_bookings")
    op.drop_index(op.f("ix_campus_sessions_id"), table_name="campus_sessions")
    op.drop_table("campus_sessions")
    # ### end Alembic commands ###
