"""add newsletter subscription field to users

Revision ID: ab53e1162c9d
Revises: eb05a92b3d10
Create Date: 2025-08-08 21:11:44.511426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab53e1162c9d"
down_revision: Union[str, None] = "eb05a92b3d10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("newsletter_subscription", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "newsletter_subscription")
    # ### end Alembic commands ###
